name: readthedocs
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pydata-sphinx-theme
  - docutils=0.20.1    # https://github.com/vidartf/nbsphinx-link/issues/22
  - m2r2
  - nbsphinx
  - nbsphinx-link
  - numpy
  - lxml-html-clean
  - ipython_genutils
